### ISSUE TITLE
Combining the Two XBOX apps

### ISSUE THREAD

**Issue by rkokkelk** [biemond/com.athom.xbox#1]
Hi,

Great work on this app for Homey. This one caught my eye because I'm also maintaining a Xbox app for Homey, but with a different goal. 

http://apps.athom.com/app/net.weejewel.xboxone 

So I was thinking maybe we can combine the two into a single app. I think that there is a great chance that the users of this application also have a Xbox connected. So how do you feel if I create a PR which combines the functionality of of my Homey app with yours?

Let me know what you think?

**Comment by biemond** [comment]
that is awesome plus its will be adding extra value to these apps. lets do it

**Comment by biemond** [comment]
How is it going? Did you already started with the PullRequest

**Comment by rkokkelk** [comment]
Hi, not yet but it is definitely on my todo list.

**Comment by biemond** [comment]
awesome , I merged it , test it without any issues plus I published v0.0.2 to athom. 


Thanks again.
